name: "Build"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - kinetic
          - melodic
          - melodicPython3
          - noetic
          - dashing
          - eloquent
          - foxy
        system:
          - x86_64-linux
          - aarch64-linux
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - uses: docker/setup-qemu-action@v1
    - uses: cachix/cachix-action@v8
      with:
        name: ros
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        skipPush: true
    - name: Cache Failed Builds
      id: cache-failed-builds
      uses: actions/cache@v1
      with:
        path: failed-builds
        key: ${{ matrix.system }}-${{ matrix.distro }}-failed-builds-${{ github.sha }}
        restore-keys: |
          ${{ matrix.system }}-${{ matrix.distro }}-failed-builds-
    - uses: ./.github/actions/nix-ros-build-action
      with:
        root-attribute: '${{ matrix.distro }}'
        system: '${{ matrix.system }}'
