name: "Build"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - kinetic
          - melodic
          - melodicPython3
          - noetic
          - dashing
          - eloquent
          - foxy
        system:
          - x86_64-linux
          - aarch64-linux
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        # Use Nix unstable to fix https://github.com/NixOS/nix/issues/1216
        install_url: https://nixos-nix-install-tests.cachix.org/serve/cvzc8mz8jp1k2iaqq5x8kvx6rh8yh3qz/install
        install_options: --tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve
        extra_nix_config: |
          extra-platforms = aarch64-linux
    - uses: docker/setup-qemu-action@v1
    - uses: cachix/cachix-action@v9
      with:
        name: ros
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        skipPush: true
    - name: Cache Failed Builds
      id: cache-failed-builds
      uses: actions/cache@v2
      with:
        path: failed-builds
        key: failed-builds-${{ matrix.distro }}-${{ matrix.system }}-${{ github.sha }}
        #restore-keys: |
        #  failed-builds-${{ matrix.distro }}-${{ matrix.system }}-
    - uses: ./.github/actions/nix-ros-build-action
      with:
        root-attribute: '${{ matrix.distro }}'
        system: '${{ matrix.system }}'
