name: Update overlay using Superflore
on:
  schedule:
    - cron: "0 12 * * FRI"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging
      - uses: cachix/install-nix-action@v13
      - name: Install Superflore
        run: |
          nix-env -f . -iA superflore
      - name: Update overlay
        env:
          # Don't use secrets.GITHUB_TOKEN because it prevents the PR from
          # triggering a build
          # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#about-workflow-events
          SUPERFLORE_GITHUB_TOKEN: ${{ secrets.SUPERFLORE_GITHUB_TOKEN }}
          ROS_OS_OVERRIDE: nixos
          ROSDEP_SOURCE_PATH: rosdep-sources
        run: |
          mkdir -p "$ROSDEP_SOURCE_PATH"
          cat << EOF > "$ROSDEP_SOURCE_PATH/20-sources.list"
          yaml https://raw.githubusercontent.com/lopsided98/rosdistro/nixos-support/rosdep/base.yaml
          yaml https://raw.githubusercontent.com/lopsided98/rosdistro/nixos-support/rosdep/python.yaml
          yaml https://raw.githubusercontent.com/lopsided98/rosdistro/nixos-support/rosdep/ruby.yaml
          EOF
          rosdep update
          git config --local user.email "superflore@github.com"
          git config --local user.name "Superflore"
          git config credential.helper '!
            f() {
              echo "username=lopsided98"
              echo "password=${SUPERFLORE_GITHUB_TOKEN}"
            }; f'
          superflore-gen-nix \
            --tar-archive-dir "${{ runner.temp }}/tar" \
            --output-repository-path . \
            --upstream-branch staging \
            --all
